#!/bin/bash

# Edit this to specify where we will install these libraries
GRASSROOTS_EXTRAS_INSTALL_PATH=/opt/grassroots/extras

JANSSON_VER=2.14
LIBUUID_VER=1.0.3
MONGO_C_VER=1.24.4
HTSLIB_VER=1.14
SQLITE_VER=3430200
PCRE_VER=8.45
LUCENE_VER=9.8.0
SOLR_VER=9.4.0



mkdir -p $GRASSROOTS_EXTRAS_INSTALL_PATH

THIS_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
echo ">>> ROOT: $THIS_PATH" 

mkdir -p temp
cd temp

# JANSSON
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/jansson/lib/libjansson.so" ]
then
	wget https://github.com/akheron/jansson/releases/download/v$JANSSON_VER/jansson-$JANSSON_VER.tar.gz
	tar xzf jansson-$JANSSON_VER.tar.gz
	cd jansson-$JANSSON_VER
	./configure --prefix=$GRASSROOTS_EXTRAS_INSTALL_PATH/jansson
	make install
fi

# LIBUUID
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/libuuid/lib/libuuid.so" ]
then
	cd $THIS_PATH/temp
	wget -O libuuid-$LIBUUID_VER.tar.gz "https://downloads.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Flibuuid%2Ffiles%2Flibuuid-$LIBUUID_VER.tar.gz%2Fdownload&ts=1532275139"  
	tar xzf libuuid-$LIBUUID_VER.tar.gz 
	cd libuuid-$LIBUUID_VER  
	./configure --prefix=$GRASSROOTS_EXTRAS_INSTALL_PATH/libuuid 
	make install  
fi

# MONGO DB C
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/mongodb-c/lib/libmongoc-1.0.so" ]
then
	cd $THIS_PATH/temp
	wget https://github.com/mongodb/mongo-c-driver/releases/download/$MONGO_C_VER/mongo-c-driver-$MONGO_C_VER.tar.gz 
	tar xzf mongo-c-driver-$MONGO_C_VER.tar.gz 
	cd mongo-c-driver-$MONGO_C_VER 
	mkdir cmake-build 
	cd cmake-build 
	cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_INSTALL_PREFIX=$GRASSROOTS_EXTRAS_INSTALL_PATH/mongodb-c .. 
	make install 
fi

# SQLITE
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/sqlite/lib/libsqlite3.so" ]
then
	cd $THIS_PATH/temp
	wget https://www.sqlite.org/2023/sqlite-amalgamation-$SQLITE_VER.zip 
	unzip sqlite-amalgamation-$SQLITE_VER.zip 
	cd sqlite-amalgamation-$SQLITE_VER 
	gcc sqlite3.c -o libsqlite3.so -shared -fPIC 
	mkdir -p $GRASSROOTS_EXTRAS_INSTALL_PATH/sqlite/include 
	mkdir -p $GRASSROOTS_EXTRAS_INSTALL_PATH/sqlite/lib 
	cp libsqlite3.so $GRASSROOTS_EXTRAS_INSTALL_PATH/sqlite/lib/ 
	cp *.h $GRASSROOTS_EXTRAS_INSTALL_PATH/sqlite/include 
fi

# HTSLIB
if [ ! -e $GRASSROOTS_EXTRAS_INSTALL_PATH/htslib/lib/libhts.so ]
then
	cd $THIS_PATH/temp
	wget https://github.com/samtools/htslib/releases/download/$HTSLIB_VER/htslib-$HTSLIB_VER.tar.bz2 
	tar xjf htslib-$HTSLIB_VER.tar.bz2 
	cd htslib-$HTSLIB_VER 
	./configure --prefix=$GRASSROOTS_EXTRAS_INSTALL_PATH/htslib --disable-bz2 --disable-lzma 
	make install 
fi

# PCRE
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/pcre/lib/libpcre.so" ]
then
	cd $THIS_PATH/temp
	wget https://altushost-swe.dl.sourceforge.net/project/pcre/pcre/$PCRE_VER/pcre-$PCRE_VER.tar.bz2 
	tar xjf pcre-$PCRE_VER.tar.bz2 
	cd pcre-$PCRE_VER 
	./configure --prefix=$GRASSROOTS_EXTRAS_INSTALL_PATH/pcre 
	make install 
fi


# LUCENE
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/lucene-$LUCENE_VER/analysis/common/lucene-analyzers-common-$LUCENE_VER.jar" ]
then
	cd $THIS_PATH/temp
	wget https://dlcdn.apache.org/lucene/java/$LUCENE_VER/lucene-$LUCENE_VER.tgz 
	tar xzf lucene-$LUCENE_VER.tgz --directory $GRASSROOTS_EXTRAS_INSTALL_PATH
	mv $GRASSROOTS_EXTRAS_INSTALL_PATH/lucene-$LUCENE_VER $GRASSROOTS_EXTRAS_INSTALL_PATH/lucene
fi


# SOLR
if [ ! -e "$GRASSROOTS_EXTRAS_INSTALL_PATH/solr-$SOLR_VER/bin/solr" ]
then
	cd $THIS_PATH/temp
	wget "https://www.apache.org/dyn/closer.lua/solr/solr/$SOLR_VER/solr-$SOLR_VER.tgz?action=download" -O solr-$SOLR_VER.tgz
	tar xzf solr-$SOLR_VER.tgz --directory $GRASSROOTS_EXTRAS_INSTALL_PATH
	mv $GRASSROOTS_EXTRAS_INSTALL_PATH/solr-$SOLR_VER $GRASSROOTS_EXTRAS_INSTALL_PATH/solr
fi


cd ..
