#!/bin/sh

#locate -b "\libcurl.so"
#
#  apt install libcurl4-gnutls-dev 
# or 
#  apt install libcurl4-nss-dev
# or  
#  apt install libcurl4-openssl-dev

GRASSROOTS_EXTRAS_INSTALL_PATH=/home/billy/test_install

mkdir -p $GRASSROOTS_EXTRAS_INSTALL_PATH

mkdir temp
cd temp

# JANSSON
if [ ! -e $GRASSROOTS_EXTRAS_INSTALL_PATH/jansson/lib/libjansson.so ]
then
	wget http://www.digip.org/jansson/releases/jansson-2.11.tar.gz
	tar xzf jansson-2.11.tar.gz
	cd jansson-2.11
	./configure --prefix=$GRASSROOTS_EXTRAS_INSTALL_PATH/jansson
	make install
	cd ..
fi

# LIBUUID
if [ ! -e $GRASSROOTS_EXTRAS_INSTALL_PATH/libuuid/lib/libuuid.so ]
then
	wget https://downloads.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Flibuuid%2Ffiles%2Flibuuid-1.0.3.tar.gz%2Fdownload&ts=1532275139
	tar xzf libuuid-1.0.3.tar.gz
	cd libuuid-1.0.3
	./configure --prefix=$GRASSROOTS_EXTRAS_INSTALL_PATH/libuuid
	make install
	cd ..
fi

